puts "loading ruby #{__FILE__}"

c = Country.find_or_create_by(name: 'Chile')

xv   = Region.find_or_create_by(short_name: 'XV Región',            name: 'Arica y Parinacota',                        code: 'XV',   country: c)
i    = Region.find_or_create_by(short_name: 'I Región',             name: 'Tarapacá',                                  code: 'I',    country: c)
ii   = Region.find_or_create_by(short_name: 'II Región',            name: 'Antofagasta',                               code: 'II',   country: c)
iii  = Region.find_or_create_by(short_name: 'III Región',           name: 'Atacama',                                   code: 'III',  country: c)
iv   = Region.find_or_create_by(short_name: 'IV Región',            name: 'Coquimbo',                                  code: 'IV',   country: c)
v    = Region.find_or_create_by(short_name: 'V Región',             name: 'Valparaíso',                                code: 'V',    country: c)
rm   = Region.find_or_create_by(short_name: 'Región Metropolitana', name: 'Metropolitana de Santiago',                 code: 'RM',   country: c)
vi   = Region.find_or_create_by(short_name: 'VI Región',            name: "Libertador General Bernardo O'Higgins",     code: 'VI',   country: c)
vii  = Region.find_or_create_by(short_name: 'VII Región',           name: 'Maule',                                     code: 'VII',  country: c)
viii = Region.find_or_create_by(short_name: 'VIII Región',          name: 'Biobío',                                    code: 'VIII', country: c)
ix   = Region.find_or_create_by(short_name: 'IX Región',            name: 'La Araucanía',                              code: 'IX',   country: c)
xiv  = Region.find_or_create_by(short_name: 'XIV Región',           name: 'Los Ríos',                                  code: 'XIV',  country: c)
x    = Region.find_or_create_by(short_name: 'X Región',             name: 'Los Lagos',                                 code: 'X',    country: c)
xi   = Region.find_or_create_by(short_name: 'XI Región',            name: 'Aisén del General Carlos Ibáñez del Campo', code: 'XI',   country: c)
xii  = Region.find_or_create_by(short_name: 'XII Región',           name: 'Magallanes y de la Antártica Chilena',      code: 'XII',  country: c)

County.find_or_create_by(name: 'Arica',                region: xv)
County.find_or_create_by(name: 'Camarones',            region: xv)
County.find_or_create_by(name: 'Putre',                region: xv)
County.find_or_create_by(name: 'General Lagos',        region: xv)
County.find_or_create_by(name: 'Iquique',              region: i)
County.find_or_create_by(name: 'Alto Hospicio',        region: i)
County.find_or_create_by(name: 'Pozo Almonte',         region: i)
County.find_or_create_by(name: 'Camiña',               region: i)
County.find_or_create_by(name: 'Colchane',             region: i)
County.find_or_create_by(name: 'Huara',                region: i)
County.find_or_create_by(name: 'Pica',                 region: i)
County.find_or_create_by(name: 'Antofagasta',          region: ii)
County.find_or_create_by(name: 'Mejillones',           region: ii)
County.find_or_create_by(name: 'Sierra Gorda',         region: ii)
County.find_or_create_by(name: 'Taltal',               region: ii)
County.find_or_create_by(name: 'Calama',               region: ii)
County.find_or_create_by(name: 'Ollagüe',              region: ii)
County.find_or_create_by(name: 'San Pedro de Atacama', region: ii)
County.find_or_create_by(name: 'Tocopilla',            region: ii)
County.find_or_create_by(name: 'María Elena',          region: ii)
County.find_or_create_by(name: 'Copiapó',              region: iii)
County.find_or_create_by(name: 'Caldera',              region: iii)
County.find_or_create_by(name: 'Tierra Amarilla',      region: iii)
County.find_or_create_by(name: 'Chañaral',             region: iii)
County.find_or_create_by(name: 'Diego de Almagro',     region: iii)
County.find_or_create_by(name: 'Vallenar',             region: iii)
County.find_or_create_by(name: 'Alto del Carmen',      region: iii)
County.find_or_create_by(name: 'Freirina',             region: iii)
County.find_or_create_by(name: 'Huasco',               region: iii)
County.find_or_create_by(name: 'La Serena',            region: iv)
County.find_or_create_by(name: 'Coquimbo',             region: iv)
County.find_or_create_by(name: 'Andacollo',            region: iv)
County.find_or_create_by(name: 'La Higuera',           region: iv)
County.find_or_create_by(name: 'Paiguano',             region: iv)
County.find_or_create_by(name: 'Vicuña',               region: iv)
County.find_or_create_by(name: 'Illapel',              region: iv)
County.find_or_create_by(name: 'Canela',               region: iv)
County.find_or_create_by(name: 'Los Vilos',            region: iv)
County.find_or_create_by(name: 'Salamanca',            region: iv)
County.find_or_create_by(name: 'Ovalle',               region: iv)
County.find_or_create_by(name: 'Combarbalá',           region: iv)
County.find_or_create_by(name: 'Monte Patria',         region: iv)
County.find_or_create_by(name: 'Punitaqui',            region: iv)
County.find_or_create_by(name: 'Río Hurtado',          region: iv)
County.find_or_create_by(name: 'Valparaíso',           region: v)
County.find_or_create_by(name: 'Casablanca',           region: v)
County.find_or_create_by(name: 'Concón',               region: v)
County.find_or_create_by(name: 'Juan Fernández',       region: v)
County.find_or_create_by(name: 'Puchuncaví',           region: v)
County.find_or_create_by(name: 'Quintero',             region: v)
County.find_or_create_by(name: 'Viña del Mar',         region: v)
County.find_or_create_by(name: 'Isla de Pascua',       region: v)
County.find_or_create_by(name: 'Los Andes',            region: v)
County.find_or_create_by(name: 'Calle Larga',          region: v)
County.find_or_create_by(name: 'Rinconada',            region: v)
County.find_or_create_by(name: 'San Esteban',          region: v)
County.find_or_create_by(name: 'La Ligua',             region: v)
County.find_or_create_by(name: 'Cabildo',              region: v)
County.find_or_create_by(name: 'Papudo',               region: v)
County.find_or_create_by(name: 'Petorca',              region: v)
County.find_or_create_by(name: 'Zapallar',             region: v)
County.find_or_create_by(name: 'Quillota',             region: v)
County.find_or_create_by(name: 'Calera',               region: v)
County.find_or_create_by(name: 'Hijuelas',             region: v)
County.find_or_create_by(name: 'La Cruz',              region: v)
County.find_or_create_by(name: 'Nogales',              region: v)
County.find_or_create_by(name: 'San Antonio',          region: v)
County.find_or_create_by(name: 'Algarrobo',            region: v)
County.find_or_create_by(name: 'Cartagena',            region: v)
County.find_or_create_by(name: 'El Quisco',            region: v)
County.find_or_create_by(name: 'El Tabo',              region: v)
County.find_or_create_by(name: 'Santo Domingo',        region: v)
County.find_or_create_by(name: 'San Felipe',           region: v)
County.find_or_create_by(name: 'Catemu',               region: v)
County.find_or_create_by(name: 'Llaillay',             region: v)
County.find_or_create_by(name: 'Panquehue',            region: v)
County.find_or_create_by(name: 'Putaendo',             region: v)
County.find_or_create_by(name: 'Santa María',          region: v)
County.find_or_create_by(name: 'Limache',              region: v)
County.find_or_create_by(name: 'Quilpué',              region: v)
County.find_or_create_by(name: 'Villa Alemana',        region: v)
County.find_or_create_by(name: 'Olmué',                region: v)
County.find_or_create_by(name: 'Rancagua',             region: vi)
County.find_or_create_by(name: 'Codegua',              region: vi)
County.find_or_create_by(name: 'Coinco',               region: vi)
County.find_or_create_by(name: 'Coltauco',             region: vi)
County.find_or_create_by(name: 'Doñihue',              region: vi)
County.find_or_create_by(name: 'Graneros',             region: vi)
County.find_or_create_by(name: 'Las Cabras',           region: vi)
County.find_or_create_by(name: 'Machalí',              region: vi)
County.find_or_create_by(name: 'Malloa',               region: vi)
County.find_or_create_by(name: 'Mostazal',             region: vi)
County.find_or_create_by(name: 'Olivar',               region: vi)
County.find_or_create_by(name: 'Peumo',                region: vi)
County.find_or_create_by(name: 'Pichidegua',           region: vi)
County.find_or_create_by(name: 'Quinta de Tilcoco',    region: vi)
County.find_or_create_by(name: 'Rengo',                region: vi)
County.find_or_create_by(name: 'Requínoa',             region: vi)
County.find_or_create_by(name: 'San Vicente',          region: vi)
County.find_or_create_by(name: 'Pichilemu',            region: vi)
County.find_or_create_by(name: 'La Estrella',          region: vi)
County.find_or_create_by(name: 'Litueche',             region: vi)
County.find_or_create_by(name: 'Marchihue',            region: vi)
County.find_or_create_by(name: 'Navidad',              region: vi)
County.find_or_create_by(name: 'Paredones',            region: vi)
County.find_or_create_by(name: 'San Fernando',         region: vi)
County.find_or_create_by(name: 'Chépica',              region: vi)
County.find_or_create_by(name: 'Chimbarongo',          region: vi)
County.find_or_create_by(name: 'Lolol',                region: vi)
County.find_or_create_by(name: 'Nancagua',             region: vi)
County.find_or_create_by(name: 'Palmilla',             region: vi)
County.find_or_create_by(name: 'Peralillo',            region: vi)
County.find_or_create_by(name: 'Placilla',             region: vi)
County.find_or_create_by(name: 'Pumanque',             region: vi)
County.find_or_create_by(name: 'Santa Cruz',           region: vi)
County.find_or_create_by(name: 'Talca',                region: vii)
County.find_or_create_by(name: 'Constitución',         region: vii)
County.find_or_create_by(name: 'Curepto',              region: vii)
County.find_or_create_by(name: 'Empedrado',            region: vii)
County.find_or_create_by(name: 'Maule',                region: vii)
County.find_or_create_by(name: 'Pelarco',              region: vii)
County.find_or_create_by(name: 'Pencahue',             region: vii)
County.find_or_create_by(name: 'Río Claro',            region: vii)
County.find_or_create_by(name: 'San Clemente',         region: vii)
County.find_or_create_by(name: 'San Rafael',           region: vii)
County.find_or_create_by(name: 'Cauquenes',            region: vii)
County.find_or_create_by(name: 'Chanco',               region: vii)
County.find_or_create_by(name: 'Pelluhue',             region: vii)
County.find_or_create_by(name: 'Curicó',               region: vii)
County.find_or_create_by(name: 'Hualañé',              region: vii)
County.find_or_create_by(name: 'Licantén',             region: vii)
County.find_or_create_by(name: 'Molina',               region: vii)
County.find_or_create_by(name: 'Rauco',                region: vii)
County.find_or_create_by(name: 'Romeral',              region: vii)
County.find_or_create_by(name: 'Sagrada Familia',      region: vii)
County.find_or_create_by(name: 'Teno',                 region: vii)
County.find_or_create_by(name: 'Vichuquén',            region: vii)
County.find_or_create_by(name: 'Linares',              region: vii)
County.find_or_create_by(name: 'Colbún',               region: vii)
County.find_or_create_by(name: 'Longaví',              region: vii)
County.find_or_create_by(name: 'Parral',               region: vii)
County.find_or_create_by(name: 'Retiro',               region: vii)
County.find_or_create_by(name: 'San Javier',           region: vii)
County.find_or_create_by(name: 'Villa Alegre',         region: vii)
County.find_or_create_by(name: 'Yerbas Buenas',        region: vii)
County.find_or_create_by(name: 'Concepción',           region: viii)
County.find_or_create_by(name: 'Coronel',              region: viii)
County.find_or_create_by(name: 'Chiguayante',          region: viii)
County.find_or_create_by(name: 'Florida',              region: viii)
County.find_or_create_by(name: 'Hualqui',              region: viii)
County.find_or_create_by(name: 'Lota',                 region: viii)
County.find_or_create_by(name: 'Penco',                region: viii)
County.find_or_create_by(name: 'San Pedro de la Paz',  region: viii)
County.find_or_create_by(name: 'Santa Juana',          region: viii)
County.find_or_create_by(name: 'Talcahuano',           region: viii)
County.find_or_create_by(name: 'Tomé',                 region: viii)
County.find_or_create_by(name: 'Hualpén',              region: viii)
County.find_or_create_by(name: 'Lebu',                 region: viii)
County.find_or_create_by(name: 'Arauco',               region: viii)
County.find_or_create_by(name: 'Cañete',               region: viii)
County.find_or_create_by(name: 'Contulmo',             region: viii)
County.find_or_create_by(name: 'Curanilahue',          region: viii)
County.find_or_create_by(name: 'Los Alamos',           region: viii)
County.find_or_create_by(name: 'Tirúa',                region: viii)
County.find_or_create_by(name: 'Los Angeles',          region: viii)
County.find_or_create_by(name: 'Antuco',               region: viii)
County.find_or_create_by(name: 'Cabrero',              region: viii)
County.find_or_create_by(name: 'Laja',                 region: viii)
County.find_or_create_by(name: 'Mulchén',              region: viii)
County.find_or_create_by(name: 'Nacimiento',           region: viii)
County.find_or_create_by(name: 'Negrete',              region: viii)
County.find_or_create_by(name: 'Quilaco',              region: viii)
County.find_or_create_by(name: 'Quilleco',             region: viii)
County.find_or_create_by(name: 'San Rosendo',          region: viii)
County.find_or_create_by(name: 'Santa Bárbara',        region: viii)
County.find_or_create_by(name: 'Tucapel',              region: viii)
County.find_or_create_by(name: 'Yumbel',               region: viii)
County.find_or_create_by(name: 'Alto Biobío',          region: viii)
County.find_or_create_by(name: 'Chillán',              region: viii)
County.find_or_create_by(name: 'Bulnes',               region: viii)
County.find_or_create_by(name: 'Cobquecura',           region: viii)
County.find_or_create_by(name: 'Coelemu',              region: viii)
County.find_or_create_by(name: 'Coihueco',             region: viii)
County.find_or_create_by(name: 'Chillán Viejo',        region: viii)
County.find_or_create_by(name: 'El Carmen',            region: viii)
County.find_or_create_by(name: 'Ninhue',               region: viii)
County.find_or_create_by(name: 'Ñiquén',               region: viii)
County.find_or_create_by(name: 'Pemuco',               region: viii)
County.find_or_create_by(name: 'Pinto',                region: viii)
County.find_or_create_by(name: 'Portezuelo',           region: viii)
County.find_or_create_by(name: 'Quillón',              region: viii)
County.find_or_create_by(name: 'Quirihue',             region: viii)
County.find_or_create_by(name: 'Ránquil',              region: viii)
County.find_or_create_by(name: 'San Carlos',           region: viii)
County.find_or_create_by(name: 'San Fabián',           region: viii)
County.find_or_create_by(name: 'San Ignacio',          region: viii)
County.find_or_create_by(name: 'San Nicolás',          region: viii)
County.find_or_create_by(name: 'Treguaco',             region: viii)
County.find_or_create_by(name: 'Yungay',               region: viii)
County.find_or_create_by(name: 'Temuco',               region: ix)
County.find_or_create_by(name: 'Carahue',              region: ix)
County.find_or_create_by(name: 'Cunco',                region: ix)
County.find_or_create_by(name: 'Curarrehue',           region: ix)
County.find_or_create_by(name: 'Freire',               region: ix)
County.find_or_create_by(name: 'Galvarino',            region: ix)
County.find_or_create_by(name: 'Gorbea',               region: ix)
County.find_or_create_by(name: 'Lautaro',              region: ix)
County.find_or_create_by(name: 'Loncoche',             region: ix)
County.find_or_create_by(name: 'Melipeuco',            region: ix)
County.find_or_create_by(name: 'Nueva Imperial',       region: ix)
County.find_or_create_by(name: 'Padre Las Casas',      region: ix)
County.find_or_create_by(name: 'Perquenco',            region: ix)
County.find_or_create_by(name: 'Pitrufquén',           region: ix)
County.find_or_create_by(name: 'Pucón',                region: ix)
County.find_or_create_by(name: 'Saavedra',             region: ix)
County.find_or_create_by(name: 'Teodoro Schmidt',      region: ix)
County.find_or_create_by(name: 'Toltén',               region: ix)
County.find_or_create_by(name: 'Vilcún',               region: ix)
County.find_or_create_by(name: 'Villarrica',           region: ix)
County.find_or_create_by(name: 'Cholchol',             region: ix)
County.find_or_create_by(name: 'Angol',                region: ix)
County.find_or_create_by(name: 'Collipulli',           region: ix)
County.find_or_create_by(name: 'Curacautín',           region: ix)
County.find_or_create_by(name: 'Ercilla',              region: ix)
County.find_or_create_by(name: 'Lonquimay',            region: ix)
County.find_or_create_by(name: 'Los Sauces',           region: ix)
County.find_or_create_by(name: 'Lumaco',               region: ix)
County.find_or_create_by(name: 'Purén',                region: ix)
County.find_or_create_by(name: 'Renaico',              region: ix)
County.find_or_create_by(name: 'Traiguén',             region: ix)
County.find_or_create_by(name: 'Victoria',             region: ix)
County.find_or_create_by(name: 'Valdivia',             region: xiv)
County.find_or_create_by(name: 'Corral',               region: xiv)
County.find_or_create_by(name: 'Lanco',                region: xiv)
County.find_or_create_by(name: 'Los Lagos',            region: xiv)
County.find_or_create_by(name: 'Máfil',                region: xiv)
County.find_or_create_by(name: 'Mariquina',            region: xiv)
County.find_or_create_by(name: 'Paillaco',             region: xiv)
County.find_or_create_by(name: 'Panguipulli',          region: xiv)
County.find_or_create_by(name: 'La Unión',             region: xiv)
County.find_or_create_by(name: 'Futrono',              region: xiv)
County.find_or_create_by(name: 'Lago Ranco',           region: xiv)
County.find_or_create_by(name: 'Río Bueno',            region: xiv)
County.find_or_create_by(name: 'Puerto Montt',         region: x)
County.find_or_create_by(name: 'Calbuco',              region: x)
County.find_or_create_by(name: 'Cochamó',              region: x)
County.find_or_create_by(name: 'Fresia',               region: x)
County.find_or_create_by(name: 'Frutillar',            region: x)
County.find_or_create_by(name: 'Los Muermos',          region: x)
County.find_or_create_by(name: 'Llanquihue',           region: x)
County.find_or_create_by(name: 'Maullín',              region: x)
County.find_or_create_by(name: 'Puerto Varas',         region: x)
County.find_or_create_by(name: 'Castro',               region: x)
County.find_or_create_by(name: 'Ancud',                region: x)
County.find_or_create_by(name: 'Chonchi',              region: x)
County.find_or_create_by(name: 'Curaco de Vélez',      region: x)
County.find_or_create_by(name: 'Dalcahue',             region: x)
County.find_or_create_by(name: 'Puqueldón',            region: x)
County.find_or_create_by(name: 'Queilén',              region: x)
County.find_or_create_by(name: 'Quellón',              region: x)
County.find_or_create_by(name: 'Quemchi',              region: x)
County.find_or_create_by(name: 'Quinchao',             region: x)
County.find_or_create_by(name: 'Osorno',               region: x)
County.find_or_create_by(name: 'Puerto Octay',         region: x)
County.find_or_create_by(name: 'Purranque',            region: x)
County.find_or_create_by(name: 'Puyehue',              region: x)
County.find_or_create_by(name: 'Río Negro',            region: x)
County.find_or_create_by(name: 'San Juan de la Costa', region: x)
County.find_or_create_by(name: 'San Pablo',            region: x)
County.find_or_create_by(name: 'Chaitén',              region: x)
County.find_or_create_by(name: 'Futaleufú',            region: x)
County.find_or_create_by(name: 'Hualaihué',            region: x)
County.find_or_create_by(name: 'Palena',               region: x)
County.find_or_create_by(name: 'Coihaique',            region: xi)
County.find_or_create_by(name: 'Lago Verde',           region: xi)
County.find_or_create_by(name: 'Aisén',                region: xi)
County.find_or_create_by(name: 'Cisnes',               region: xi)
County.find_or_create_by(name: 'Guaitecas',            region: xi)
County.find_or_create_by(name: 'Cochrane',             region: xi)
County.find_or_create_by(name: 'O\'Higgins',           region: xi)
County.find_or_create_by(name: 'Tortel',               region: xi)
County.find_or_create_by(name: 'Chile Chico',          region: xi)
County.find_or_create_by(name: 'Río Ibáñez',           region: xi)
County.find_or_create_by(name: 'Punta Arenas',         region: xii)
County.find_or_create_by(name: 'Laguna Blanca',        region: xii)
County.find_or_create_by(name: 'Río Verde',            region: xii)
County.find_or_create_by(name: 'San Gregorio',         region: xii)
County.find_or_create_by(name: 'Cabo de Hornos',       region: xii)
County.find_or_create_by(name: 'Antártica',            region: xii)
County.find_or_create_by(name: 'Porvenir',             region: xii)
County.find_or_create_by(name: 'Primavera',            region: xii)
County.find_or_create_by(name: 'Timaukel',             region: xii)
County.find_or_create_by(name: 'Natales',              region: xii)
County.find_or_create_by(name: 'Torres del Paine',     region: xii)
County.find_or_create_by(name: 'Colina',               region: rm)
County.find_or_create_by(name: 'Lampa',                region: rm)
County.find_or_create_by(name: 'Tiltil',               region: rm)
County.find_or_create_by(name: 'Pirque',               region: rm)
County.find_or_create_by(name: 'Puente Alto',          region: rm)
County.find_or_create_by(name: 'San José de Maipo',    region: rm)
County.find_or_create_by(name: 'Buin',                 region: rm)
County.find_or_create_by(name: 'Calera de Tango',      region: rm)
County.find_or_create_by(name: 'Paine',                region: rm)
County.find_or_create_by(name: 'San Bernardo',         region: rm)
County.find_or_create_by(name: 'Alhué',                region: rm)
County.find_or_create_by(name: 'Curacaví',             region: rm)
County.find_or_create_by(name: 'María Pinto',          region: rm)
County.find_or_create_by(name: 'Melipilla',            region: rm)
County.find_or_create_by(name: 'San Pedro',            region: rm)
County.find_or_create_by(name: 'Cerrillos',            region: rm)
County.find_or_create_by(name: 'Cerro Navia',          region: rm)
County.find_or_create_by(name: 'Conchalí',             region: rm)
County.find_or_create_by(name: 'El Bosque',            region: rm)
County.find_or_create_by(name: 'Estación Central',     region: rm)
County.find_or_create_by(name: 'Huechuraba',           region: rm)
County.find_or_create_by(name: 'Independencia',        region: rm)
County.find_or_create_by(name: 'La Cisterna',          region: rm)
County.find_or_create_by(name: 'La Granja',            region: rm)
County.find_or_create_by(name: 'La Florida',           region: rm)
County.find_or_create_by(name: 'La Pintana',           region: rm)
County.find_or_create_by(name: 'La Reina',             region: rm)
County.find_or_create_by(name: 'Las Condes',           region: rm)
County.find_or_create_by(name: 'Lo Barnechea',         region: rm)
County.find_or_create_by(name: 'Lo Espejo',            region: rm)
County.find_or_create_by(name: 'Lo Prado',             region: rm)
County.find_or_create_by(name: 'Macul',                region: rm)
County.find_or_create_by(name: 'Maipú',                region: rm)
County.find_or_create_by(name: 'Ñuñoa',                region: rm)
County.find_or_create_by(name: 'Pedro Aguirre Cerda',  region: rm)
County.find_or_create_by(name: 'Peñalolén',            region: rm)
County.find_or_create_by(name: 'Providencia',          region: rm)
County.find_or_create_by(name: 'Pudahuel',             region: rm)
County.find_or_create_by(name: 'Quilicura',            region: rm)
County.find_or_create_by(name: 'Quinta Normal',        region: rm)
County.find_or_create_by(name: 'Recoleta',             region: rm)
County.find_or_create_by(name: 'Renca',                region: rm)
County.find_or_create_by(name: 'San Miguel',           region: rm)
County.find_or_create_by(name: 'San Joaquín',          region: rm)
County.find_or_create_by(name: 'San Ramón',            region: rm)
County.find_or_create_by(name: 'Santiago',             region: rm)
County.find_or_create_by(name: 'Vitacura',             region: rm)
County.find_or_create_by(name: 'El Monte',             region: rm)
County.find_or_create_by(name: 'Isla de Maipo',        region: rm)
County.find_or_create_by(name: 'Padre Hurtado',        region: rm)
County.find_or_create_by(name: 'Peñaflor',             region: rm)
County.find_or_create_by(name: 'Talagante',            region: rm)
