puts "loading ruby #{__FILE__}"

Country.find_or_create_by :name => "Afghanistan", :code => "AF"
Country.find_or_create_by :name => "Aland Islands", :code => "AX"
Country.find_or_create_by :name => "Albania", :code => "AL"
Country.find_or_create_by :name => "Algeria", :code => "DZ"
Country.find_or_create_by :name => "American Samoa", :code => "AS"
Country.find_or_create_by :name => "Andorra", :code => "AD"
Country.find_or_create_by :name => "Angola", :code => "AO"
Country.find_or_create_by :name => "Anguilla", :code => "AI"
Country.find_or_create_by :name => "Antarctica", :code => "AQ"
Country.find_or_create_by :name => "Antigua and Barbuda", :code => "AG"
Country.find_or_create_by :name => "Argentina", :code => "AR"
Country.find_or_create_by :name => "Armenia", :code => "AM"
Country.find_or_create_by :name => "Aruba", :code => "AW"
Country.find_or_create_by :name => "Australia", :code => "AU"
Country.find_or_create_by :name => "Austria", :code => "AT"
Country.find_or_create_by :name => "Azerbaijan", :code => "AZ"
Country.find_or_create_by :name => "Bahamas", :code => "BS"
Country.find_or_create_by :name => "Bahrain", :code => "BH"
Country.find_or_create_by :name => "Bangladesh", :code => "BD"
